### PR TITLE
Event refactoring

### PR DESCRIPTION
**Pull request by fairlight1337**
I'm SORRY for the every long pull request. I started using separate branches for new feature pull requests after having accumulated a bunch of commits in this one already; this is the last time, promise ;).

It mainly consists of:
- MoveIt! interface refactoring (callable CRAM functions stay the same)
- Moved `cram_moveit`-specific functions into `cram_moveit` instead of having them sit around and create dependency problems in `robosherlock_process_module`
- Added ACL (Agent Communication Language) package that allows for (de-)serialization of KQML strings (inter-robot communication); creates no dependencies and is stand-alone for now

### CODE REVIEW

**Comment by gaya-** [comment]
Hey Jan, I'm not using cram_bridge at the moment and only cherry-picking bug-fixes into my own repos. So you can merge changes in cram_moveit without issuing pull requests, or at least I won't be able to test anything. The rest of cram_bridge management I leave to Georg I guess.

**Comment by fairlight1337** [comment]
Okay, I resolved part of the pull request myself by merging in the relevant parts from other pull requests (that only affect my code). So this should be way less code here now.

This is the companion pull request of this, by the way: https://github.com/cram-code/cram_highlevel/pull/49

The one at hand here uses symbols exported by the other one.

**Comment by gaya-** [comment]
Haha, looks much neater now :)

**Comment by gaya-** [comment]
`cram_moveit` commits are merged in the cram2 repo.
`robosherlock_process_module` changes are deprecated or also committed in the cram2 repos.
So I'm closing this PR to not leave open questions.

**Pull request closed without merging**
