### PR TITLE
Catkinization.

### PR DESCRIPTION
**Pull request by mpomarlan**
More or less straightforward catkinization.

WARNING: removed cram_beasty. It depends on a hidden package (dlr_messages) and it might be better not to have a public package that cannot be compiled because of a proprietary dependency. If needed in cram_bridge (as opposed to a special meta_package we'd keep hidden), beasty code can be restored, of course.

NOTES on dependecies:

-most- of cram_bridge dependencies have been catkinized for ages, however some were not, and were catkinized just prior to this pull request, and are themselves pending pull request acceptance. To ease tracking, here is a list of dependencies and where to get them, pending pull requests:

- cram_pr2: until pull request #9 is merged, use branch https://github.com/mpomarlan/cram_pr2.git
- ias_common: until pull request #1 is merged, use branch https://github.com/mpomarlan/ias_common.git
- wsg50: use the code from https://github.com/code-iai/iai_robot_drivers.git

### CODE REVIEW

**Comment by airballking** [comment]
All the upstream pull requests have been resolved, and I removed ```cram_beasty```. However, now auto-merging this pull request does not work any longer. @mpomarlan Could you please update your pull request? Sorry for the inconvenience.

**Comment by mpomarlan** [comment]
Conflicts should be resolved now.
Cheers.

**Comment by airballking** [comment]
@mpomarlan Perfect, thanks!

**Comment by gaya-** [comment]
@airballking , did you remove your ```devel``` and ```build``` directories before testing if this compiles?
In any case, ```cram_wsg50``` package has non-corresponding dependencies between ```package.xml``` and ```CMakeLists.txt```, at least add a ```cram_language``` into the ```package.xml```, although I don't think it's needed.

This is just one example that my student found, maybe you should go through the other packages and check if they compile as well. One easy hacky solution would be to get rid of all the Lisp package deps in ```CMakeLists``` if you're feeling lazy...

**Comment by mpomarlan** [comment]
I did (remove build, devel).

catkin_make completes successfully.

**Comment by gaya-** [comment]
Well, I don't care about this package, do as you please you guys. I'm just saying that package.xml and CMakeLists.txt should have the same dependencies. I myself am gonna put a CATKIN_IGNORE everywhere where I'm not using the stuff. I don't know how to resolve all the dependencies in all the package.xml-s of this metapackage anyway... I wish there was a better way to distribute the single packages, so that one wouldn't have to get 10 extra repos (e.g. designator_integration_lisp, cl_feature_constraints, fccl_msgs, wsg_50_common) just to be able to use, say, ```cram_json_prolog```.

**Comment by mpomarlan** [comment]
Lol, the dependencies in cram_bridge were indeed byzantine- see the comment at the top of the pull request. Those are just the (meta)packages that needed catkinizing too, and there's more dependencies than that.

It's an artifact of cram_bridge not beeing more thematic, I think. It's just a dumping ground for cram stuff that's not quite core.

**Comment by airballking** [comment]
@gaya- I did ```catkin_make``` the repo in a workspace with other of our repos present. I fixed the two issues I encountered in this process (see my commits from yesterday).

On a related note, I sincerely hope that all my colleagues follow a similar approach: Fix small issues you see and can solve yourself, otherwise open a specific issue on the respective repository.

Regarding 'I wish I could just compile ```cram_json_prolog``` without needing ```fccl_msgs```' (I'm paraphrasing), I think this criticism should (to a large extent) be directed at the people who designed ```catkin```.

**Comment by gaya-** [comment]
> On a related note, I sincerely hope that all my colleagues follow a similar approach: Fix small issues you see and can solve yourself, otherwise open a specific issue on the respective repository.

I do try to fix small issues that I can fix. In this particular case I could not contribute a fix because (1) it was my student who had a problem with the cram_wsg50 and I don't think students should be forced to contribute fixes, (2) I myself don't have the necessary dependencies to compile this particular package and I am not willing to install them just for that one reason, (3) it turns out that having a missing package dependency in a package.xml that is present in CMakeLists doesn't cause compilation errors; it can cause problems when installing a package as a debian though, so as for now it is not an urgent problem to be opening up a new issue, consider it as a general code review comment.

**Pull request merged**
